# Generated by Django 3.1.4 on 2020-12-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='razão social')),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='descrição')),
                ('salario', models.FloatField()),
                ('requisitos', models.TextField()),
                ('escolaridade', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.CharField(max_length=255, verbose_name='experiência')),
                ('ultima_escolaridade', models.CharField(max_length=60)),
                ('pretensao_salarial', models.FloatField(verbose_name='pretensão salarial')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.vaga')),
            ],
        ),
    ]
