# Generated by Django 3.1.4 on 2020-12-07 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCEscolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='pccandidatura',
            name='ultima_escolaridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pcescolaridade'),
        ),
    ]
