# Generated by Django 3.1.4 on 2020-12-08 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_pcfaixasalarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pccandidatura',
            name='pretensao_salarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pcfaixasalarial'),
        ),
    ]
