# Generated by Django 3.1.4 on 2020-12-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20201207_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcvaga',
            name='escolaridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pcescolaridade'),
        ),
    ]
