# Generated by Django 3.1.4 on 2020-12-20 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20201208_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcvaga',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
